### ISSUE TITLE
Cannot read property 'length' of null error after upgrading to v0.7.4

### ISSUE THREAD

**Issue by kyrylkov** [vkarpov15/mongoose-lean-virtuals#45]
```
TypeError: Cannot read property 'length' of null
    at applyVirtualsToChildren (C:\Users\usr\dev\ew\node_modules\mongoose-lean-virtuals\index.js:127:26)
    at model.Query.attachVirtuals (C:\Users\usr\dev\ew\node_modules\mongoose-lean-virtuals\index.js:79:3)
    at model.Query.<anonymous> (C:\Users\usr\dev\ew\node_modules\mongoose-lean-virtuals\index.js:52:22)
    at C:\Users\usr\dev\ew\node_modules\mongoose-lean-virtuals\index.js:13:12
    at C:\Users\usr\dev\ew\node_modules\mongoose\lib\query.js:4429:15
    at cb (C:\Users\usr\dev\ew\node_modules\mongoose\lib\query.js:1907:9)
    at C:\Users\usr\dev\ew\node_modules\mongodb\lib\utils.js:677:5
    at handleCallback (C:\Users\usr\dev\ew\node_modules\mongodb\lib\utils.js:102:55)
    at C:\Users\usr\dev\ew\node_modules\mongodb\lib\cursor.js:838:66
    at C:\Users\usr\dev\ew\node_modules\mongodb\lib\utils.js:677:5
    at C:\Users\usr\dev\ew\node_modules\mongodb\lib\cursor.js:923:9
    at Cursor._endSession (C:\Users\usr\dev\ew\node_modules\mongodb\lib\core\cursor.js:394:7)
    at C:\Users\usr\dev\ew\node_modules\mongodb\lib\cursor.js:921:12
    at maybePromise (C:\Users\usr\dev\ew\node_modules\mongodb\lib\utils.js:665:3)
    at Cursor.close (C:\Users\usr\dev\ew\node_modules\mongodb\lib\cursor.js:914:12)
    at C:\Users\usr\dev\ew\node_modules\mongodb\lib\cursor.js:838:27
    at handleCallback (C:\Users\usr\dev\ew\node_modules\mongodb\lib\core\cursor.js:31:5)
    at C:\Users\usr\dev\ew\node_modules\mongodb\lib\core\cursor.js:680:38
    at _setCursorNotifiedImpl (C:\Users\usr\dev\ew\node_modules\mongodb\lib\core\cursor.js:693:10)
    at setCursorNotified (C:\Users\usr\dev\ew\node_modules\mongodb\lib\core\cursor.js:680:3)
    at setCursorDeadAndNotified (C:\Users\usr\dev\ew\node_modules\mongodb\lib\core\cursor.js:673:3)
    at nextFunction (C:\Users\usr\dev\ew\node_modules\mongodb\lib\core\cursor.js:827:5)
```

**Comment by bamse16** [comment]
Getting the same. Most likely related to https://github.com/vkarpov15/mongoose-lean-virtuals/blob/ff50e2cc48b6e896cda41919e8fcb15094c71e0c/index.js#L127 that's set to null at #L115.

**Comment by vkarpov15** [comment]
Fixed by https://github.com/vkarpov15/mongoose-lean-virtuals/pull/44
